apiVersion: v1
kind: ConfigMap
metadata:
  name: carvedrockapi-configmap
annotations:
  fluxcd.io/ignore: "false"
  fluxcd.io/automated: "true"
data:
  appsettings.json: |-
    {
      "Serilog": {
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "System": "Warning"
          }
        }
      },
      "AllowedHosts": "*"
    }