---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: carvedrockpipelineapi
  name: carvedrockpipelineapi
  annotations:
    fluxcd.io/ignore: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: carvedrockpipelineapi
