apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "carvedrockpipelineapi.fullname" . }}
  labels:
    {{- include "carvedrockpipelineapi.labels" . | nindent 4 }}
spec:
  defaultBackend:
    service:
      name: carvedrockpipelineapi
      port: 
        number: 80
  rules:
  - host: carved.rock.api
    http:
      paths:
      - backend:
          service:
            name: carvedrockpipelineapi
            port: 
              number: 80
        pathType: ImplementationSpecific
