apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carvedrockpipelineapi-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  chart:
    git: ssh://git@github.com/pauljmartin16/gitops-carvedrockpipelineapi.git
    path: helm/chart
    ref: main
  rollback:
    enable: true
    retry: true
